// Thin wrapper around the OpenNext-generated worker that adds Cloudflare Cron Trigger
// support. .open-next/worker.js is fully regenerated by `npm run build:cf`, so this file
// (not that one) is what wrangler.toml points `main` at — it survives rebuilds.
import openNextWorker, { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "./.open-next/worker.js";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// Maps the exact cron string (from wrangler.toml [triggers]) to the internal route it runs.
const CRON_ROUTES = {
  "0 3 * * *": "/api/cron/refresh-recalls",
};

export default {
  fetch: openNextWorker.fetch,
  async scheduled(event, env, ctx) {
    const path = CRON_ROUTES[event.cron];
    if (!path) return;
    const req = new Request(`https://carissues.co.il${path}`, {
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(openNextWorker.fetch(req, env, ctx));
  },
};
